name: Deploy Frontend and Admin to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Step 4: Copy frontend build to EC2
      - name: Deploy frontend build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "frontend/dist/"
          target: "/var/www/html/frontend"
          strip_components: 1

      # Step 5: Build admin panel
      - name: Build admin panel
        run: |
          cd admin
          npm install
          npm run build

      # Step 6: Copy admin build to EC2
      - name: Deploy admin build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "admin/dist/"
          target: "/var/www/html/admin"
          strip_components: 1

      # Step 7: Restart Nginx on EC2
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart nginx
